version: "3.8"
services:
    semester-project-database:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3306:3306"
    database-explorer:
        image: phpmyadmin
        restart: always
        ports:
            - 8037:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: semester-project-database
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: secret
